services:
  patient-service:
    build: ./patient-service
    ports:
      - "8091:8080"
    environment:
      - PORT=8080
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8081
    depends_on:
      - appointment-service

  appointment-service:
    build: ./appointment-service
    ports:
      - "8092:8081"
    environment:
      - PORT=8081
