apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # Health check
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port

    # ðŸ”¥ Rewrite rules
    alb.ingress.kubernetes.io/actions.appointment-rewrite: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"appointment-service","servicePort":"80"}]}}

    alb.ingress.kubernetes.io/actions.patient-rewrite: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"patient-service","servicePort":"80"}]}}

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /appointment
            pathType: Prefix
            backend:
              service:
                name: appointment-service
                port:
                  number: 80

          - path: /patient
            pathType: Prefix
            backend:
              service:
                name: patient-service
                port:
                  number: 80
