apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port

    # -------- Appointment rewrite --------
    alb.ingress.kubernetes.io/actions.appointment-action: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"appointment-service","servicePort":"80"}]}}

    alb.ingress.kubernetes.io/conditions.appointment-action: >
      [{"field":"path-pattern","pathPatternConfig":{"values":["/appointment","/appointment/*"]}}]

    # -------- Patient rewrite --------
    alb.ingress.kubernetes.io/actions.patient-action: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"patient-service","servicePort":"80"}]}}

    alb.ingress.kubernetes.io/conditions.patient-action: >
      [{"field":"path-pattern","pathPatternConfig":{"values":["/patient","/patient/*"]}}]

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /appointment
            pathType: Prefix
            backend:
              service:
                name: appointment-action
                port:
                  name: use-annotation

          - path: /patient
            pathType: Prefix
            backend:
              service:
                name: patient-action
                port:
                  name: use-annotation
